version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello, world!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
