version: 2.1

jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - run:
          name: First Hello World
          command: echo "Its Vishal First Hello World..."
      - run:
          name: Sleep
          command: sleep 25

  two:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run:
          name: Second Hello
          command: echo "Hello Vishal...."
      - run:
          name: Sleep
          command: sleep 15

workflows:
  one_and_two:
    jobs:
      - one
      - two
